services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: myappdb       # Nome do banco de dados
      POSTGRES_USER: myuser      # Nome do usuário do banco de dados
      POSTGRES_PASSWORD: mypass  # Senha do usuário do banco de dados
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local